### ISSUE TITLE
Merge leftovers problem

### ISSUE THREAD

**Issue by mereolog** [iofoundry/ontology#20]
There are some leftovers from an unfinished merged in Core ontology: https://github.com/iofoundry/ontology/blob/ef6f0bc734d5a04282b4236cbac66c26907060eb/core/Core.rdf#L3423-L3462.
This makes [Core ontology](https://github.com/iofoundry/ontology/blob/master/core/Core.rdf) syntactically incorrect.

**Comment by MilosDrobnjakovic** [comment]
Pushed a new commit that should address the issue.

**Comment by mereolog** [comment]
Indeed, it is fixed now.
