### ISSUE TITLE
Version info for AnnotationVocabulary.rdf

### ISSUE THREAD

**Issue by mereolog** [iofoundry/ontology#37]
Is this correct?

https://github.com/iofoundry/ontology/blob/4193612f5c7fd869c48fcb0d8ebdb06be32019ae/core/meta/AnnotationVocabulary.rdf#L33

**Comment by wsobel** [comment]
Is this for the prior version? I’m not quite sure. The beta was tagged 2022-05-06. We removed the dev IRI, so not quite sure what the version info os addressing. BestW(Sent from mobile)On Jan 31, 2023, at 18:35, Pawel Garbacz ***@***.***> wrote:﻿
Is this correct?
https://github.com/iofoundry/ontology/blob/4193612f5c7fd869c48fcb0d8ebdb06be32019ae/core/meta/AnnotationVocabulary.rdf#L33

**Comment by wsobel** [comment]
From the doc:versionInfo – owl:versionInfoDefinition:  owl:versionInfo provides the release version number of the ontologyOntologies MUST have an owl:versionInfo annotationThe versionInfo MUST have the numeric version component (YYYYNN) of the release version IRI as the valueSee Public Release Version IRI in the IRI Structure and Format V2.1 document.This does not make sense for ontologies that are not released. For the released ontologies: 202301Otherwise we can leave it out for maintenance and SC. BestW(Sent from mobile)On Jan 31, 2023, at 19:58, William Sobel ***@***.***> wrote:﻿Is this for the prior version? I’m not quite sure. The beta was tagged 2022-05-06. We removed the dev IRI, so not quite sure what the version info os addressing. BestW(Sent from mobile)On Jan 31, 2023, at 18:35, Pawel Garbacz ***@***.***> wrote:﻿
Is this correct?
https://github.com/iofoundry/ontology/blob/4193612f5c7fd869c48fcb0d8ebdb06be32019ae/core/meta/AnnotationVocabulary.rdf#L33

**Comment by chris-will** [comment]
I would think per our rules and the fact we are releasing this tomorrow or sometime this week along with Core, that you need to go with the IRI rules v2.1. So, that would be more like:
<owl:versionIRI rdf:resource="https://spec.industrialontologies.org/ontology/202301/core/meta/AnnotationVocabulary/"/>
<owl:versionInfo xml:lang="en-US">Version 1, Release 2023-01</owl:versionInfo>

**Comment by chris-will** [comment]
Also, while you are at it, please revise and re-sequence the change notes (ascending order by date) as follows:

<skos:changeNote xml:lang="en-US">added new annotations perperties as per &quot;Annotations Vocabulary Version 1&quot; - 31 March 2022</skos:changeNote>
<skos:changeNote xml:lang="en-US">added new annotations and supporting constructs, and modified others to match revised guidance of the &quot;Annotations Vocabulary Version 2&quot; - August and September 2022</skos:changeNote>
<skos:changeNote xml:lang="en-US">revised the IRI structure to correspond to the approved approach to IRI representation documented in https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/3564372109/IRI+Structure+and+Format and ran the RDF serialiser (from FIBO) over the content; - October 2022</skos:changeNote>
<skos:changeNote xml:lang="en-US">revised/added and existing/new annotations perperties to match revised guidance for formalizing terms as per &quot;Annotations Vocabulary Version 2.1&quot; ; - November 2022</skos:changeNote>

**Comment by chris-will** [comment]
...and lastly, might as well update the copyright statement here to: 

<iof-av:copyright>Copyright (c) 2022, 2023, Open Applications Group</iof-av:copyright>

**Comment by ekwallace** [comment]
The changes suggested below are fine, except please change occurrences of “perperties” within the suggested changeNotes to “properties”.

From: Chris Will ***@***.***>
Reply-To: iofoundry/ontology ***@***.***>
Date: Tuesday, January 31, 2023 at 5:54 PM
To: iofoundry/ontology ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [iofoundry/ontology] Version info for AnnotationVocabulary.rdf (Issue #37)


Also, while you are at it, please revise and re-sequence the change notes (ascending order by date) as follows:

<skos:changeNote xml:lang="en-US">added new annotations perperties as per "Annotations Vocabulary Version 1" - 31 March 2022</skos:changeNote>
<skos:changeNote xml:lang="en-US">added new annotations and supporting constructs, and modified others to match revised guidance of the "Annotations Vocabulary Version 2" - August and September 2022</skos:changeNote>
<skos:changeNote xml:lang="en-US">revised the IRI structure to correspond to the approved approach to IRI representation documented in https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/3564372109/IRI+Structure+and+Format<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Foagiscore.atlassian.net%2Fwiki%2Fspaces%2FIOF%2Fpages%2F3564372109%2FIRI%2BStructure%2Band%2BFormat&data=05%7C01%7Cevan.wallace%40nist.gov%7C5fa2d5c60bee4bd3fdcc08db03de1d31%7C2ab5d82fd8fa4797a93e054655c61dec%7C1%7C0%7C638108024745617471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oxx3CgwrEJV8ecosbZILd5JZX8pRzCu6oXJITStehPY%3D&reserved=0> and ran the RDF serialiser (from FIBO) over the content; - October 2022</skos:changeNote>
<skos:changeNote xml:lang="en-US">revised/added and existing/new annotations perperties to match revised guidance for formalizing terms as per "Annotations Vocabulary Version 2.1" ; - November 2022</skos:changeNote>

**Comment by wsobel** [comment]
According to the doc, it’s only three number: <owl:versionInfo xml:lang="en-US">202301</owl:versionInfo>(Sent from mobile)On Jan 31, 2023, at 23:44, Chris Will ***@***.***> wrote:﻿
I would think per our rules and the fact we are releasing this tomorrow or sometime this week along with Core, that you need to go with the IRI rules v2.1. So, that would be more like:
<owl:versionIRI rdf:resource="https://spec.industrialontologies.org/ontology/202301/core/meta/AnnotationVocabulary/"/>
<owl:versionInfo xml:lang="en-US">Version 1, Release 2023-01</owl:versionInfo>

**Comment by mereolog** [comment]
As for:

> Also, while you are at it, please revise and re-sequence the change notes (ascending order by date) as follows:
> 
> <skos:changeNote xml:lang="en-US">added new annotations perperties as per "Annotations Vocabulary Version 1" - 31 March 2022</skos:changeNote>
> <skos:changeNote xml:lang="en-US">added new annotations and supporting constructs, and modified others to match revised guidance of the "Annotations Vocabulary Version 2" - August and September 2022</skos:changeNote>
> <skos:changeNote xml:lang="en-US">revised the IRI structure to correspond to the approved approach to IRI representation documented in [https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/3564372109/IRI+Structure+and+Format<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Foagiscore.atlassian.net%2Fwiki%2Fspaces%2FIOF%2Fpages%2F3564372109%2FIRI%2BStructure%2Band%2BFormat&data=05%7C01%7Cevan.wallace%40nist.gov%7C5fa2d5c60bee4bd3fdcc08db03de1d31%7C2ab5d82fd8fa4797a93e054655c61dec%7C1%7C0%7C638108024745617471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oxx3CgwrEJV8ecosbZILd5JZX8pRzCu6oXJITStehPY%3D&reserved=0](https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/3564372109/IRI+Structure+and+Format%3Chttps://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Foagiscore.atlassian.net%2Fwiki%2Fspaces%2FIOF%2Fpages%2F3564372109%2FIRI%2BStructure%2Band%2BFormat&data=05%7C01%7Cevan.wallace%40nist.gov%7C5fa2d5c60bee4bd3fdcc08db03de1d31%7C2ab5d82fd8fa4797a93e054655c61dec%7C1%7C0%7C638108024745617471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oxx3CgwrEJV8ecosbZILd5JZX8pRzCu6oXJITStehPY%3D&reserved=0)> and ran the RDF serialiser (from FIBO) over the content; - October 2022</skos:changeNote>
> <skos:changeNote xml:lang="en-US">revised/added and existing/new annotations perperties to match revised guidance for formalizing terms as per "Annotations Vocabulary Version 2.1" ; - November 2022</skos:changeNote>

I am afraid that this is not possible - the order of statements in the file is set by the serialiser and the benefits of using it overweigh, in my view, the benefits of having a group of statements in a certain order. Also the order of such statements is always volatile and may change from one ontology editor to another.

**Comment by ekwallace** [comment]
I’m confused.  I personally would prefer something like “Version 1, Release 2023-01”
But the 2.1 version of the IOF Annotation Property Guide in Confluence says

***@***.***
I’m all for changing this going forward.  Right now what it requires is redundant with the content of the Ontology Version IRI and adds no value, and is, at best, ambiguous about how to use it for post release versions in GitHub.

BTW – we should change the title of the IRI Confluence page to better reflect its full content.  I am still surprised to see guidance other than about IRI construction within it.  It would be better to call it “IRI Structure and Construct Naming Rules.

-Evan

**Comment by wsobel** [comment]
Created issue https://oagiscore.atlassian.net/browse/ARCH-40 

Best, 
W

**Comment by wsobel** [comment]
Already done: https://oagiscore.atlassian.net/browse/ARCH-40
