### ISSUE TITLE
Wrong IRI in SupplyChainReferenceOntology.rdf

### ISSUE THREAD

**Issue by mereolog** [iofoundry/ontology#45]
supplychain ontology contains wrong IRI for the iof-av ontology: instead of https://spec.industrialontologies.org/ontology/core/meta/iof-av/ it should have https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/ - see:
https://github.com/iofoundry/ontology/blob/adc3d27219915f229ecd4a53e769e681da4f3cb9/supplychain/SupplyChainReferenceOntology.rdf#L5
and
https://github.com/iofoundry/ontology/blob/adc3d27219915f229ecd4a53e769e681da4f3cb9/supplychain/SupplyChainReferenceOntology.rdf#L17

**Comment by fameri** [comment]
the IRI for iof-av is fixed in the branch. The ontology name is still SupplyChainReferenceOntolgy.rdf. Does the hygiene test work if the file is renamed to SupplyChain.rdf?

**Comment by mereolog** [comment]
> the IRI for iof-av is fixed in the branch. The ontology name is still SupplyChainReferenceOntolgy.rdf. Does the hygiene test work if the file is renamed to SupplyChain.rdf?

Yes, hygiene test will work after the rename provided that either the ontology is resolvable or https://github.com/iofoundry/ontology/blob/master/catalog-v001.xml file contains the pointer to the appropriate file in the file system.
