### ISSUE TITLE
Typo in "iof-av"

### ISSUE THREAD

**Issue by przemekgradzki** [iofoundry/ontology#48]
https://github.com/iofoundry/ontology/blob/adc3d27219915f229ecd4a53e769e681da4f3cb9/supplychain/SupplyChainReferenceOntology.rdf#L5

should be:
```
<!ENTITY iof-av "https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/"> 
```

https://github.com/iofoundry/ontology/blob/adc3d27219915f229ecd4a53e769e681da4f3cb9/supplychain/SupplyChainReferenceOntology.rdf#L17

should be:
```
xmlns:iof-av="https://spec.industrialontologies.org/ontology/core/meta/AnnotationVocabulary/"
```

Introduced in [@MilosDrobnjakovic Updated SCRO to the latest available version](https://github.com/iofoundry/ontology/pull/41/commits/7f929d620f1016ce27f6f6d671844c533fb4ddd4)

**Comment by mereolog** [comment]
Same issue reported here https://github.com/iofoundry/ontology/issues/45.
